=== ES-DOC/django-cim-forms/CIM_Questionnaire/dcf/static/dcf/xml/vocabulary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- configuration.xsd -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    
    <xs:annotation>
        <xs:documentation>
            This schema defines the format of vocabulary files for the DCF Application.
            A vocabulary file defines properties and constraints among properties for CIM documents.
            This schema is a simplification of the Metafor CV (mindmap) standard.  Full support for mindmaps is forthcoming.
        </xs:documentation>
    </xs:annotation>
    
    <xs:element name="vocabulary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="models">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="model" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="NonEmptyStringType"/>
                                        <xs:element name="properties">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="unique_models">
                        <xs:selector xpath="./model"/>
                        <xs:field xpath="name"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PropertyType">
        <xs:sequence>
            <xs:element name="shortName" type="NonEmptyStringType"/>
            <xs:element name="longName" type="NonEmptyStringType"/>
            <xs:choice >
                <xs:element name="properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>            
                <xs:element name="values">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value" type="PropertyValueType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attributeGroup ref="PropertyValueAttributeGroup"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
        
    <xs:attributeGroup name="PropertyValueAttributeGroup">
        <!-- these are all false unless otherwise specified -->
        <xs:attribute name="open" type="xs:boolean"/>
        <xs:attribute name="multi" type="xs:boolean"/>
        <xs:attribute name="nullable" type="xs:boolean"/>
    </xs:attributeGroup>
    
    <xs:complexType name="PropertyValueType">
        <xs:sequence>
            <xs:element name="shortName" type="NonEmptyStringType"/>
            <xs:element name="longName" type="NonEmptyStringType" minOccurs="0"/>
        </xs:sequence>    
    </xs:complexType>
    
    <xs:simpleType name="NonEmptyStringType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>    
    </xs:simpleType>
    
</xs:schema>

=== ES-DOC/django-cim-forms/dcf/sample_media/dycore_vocabulary.xml
<?xml version="1.0" encoding="UTF-8"?>
<vocabulary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="file:/home/likewise-open/WX/allyn.treshansky/Dropbox/WORK/COELACANTH/CIM_editor/site_media/dcf/vocabularies/vocabulary.xsd">
  <models>
    <model>
      <name>modelcomponent</name>
      <properties>
        <property>
          <shortName>dycore_properties</shortName>
          <longName>Dycore Properties</longName>
          <properties>
              <property>
                <shortName>equation_set</shortName>
                <longName>Equation Set</longName>
                <values open="true">
                  <value>
                    <shortName>deep-atmosphere non-hydrostatic (unapproximated Euler                equations)</shortName>
                    <longName>deep-atmosphere non-hydrostatic (unapproximated Euler equations)</longName>
                  </value>
                  <value>
                    <shortName>deep-atmosphere, non-hydrostatic, spherical geopotential                approximation</shortName>
                    <longName>deep-atmosphere, non-hydrostatic, spherical geopotential                approximation</longName>
                  </value>
                  <value>
                    <shortName>deep-atmosphere, hydrostatic, spherical geopotential approximation                (quasi-hydrostatic)</shortName>
                    <longName>deep-atmosphere, hydrostatic, spherical geopotential approximation                (quasi-hydrostatic)</longName>
                  </value>
                  <value>
                    <shortName>shallow-atmosphere, non-hydrostatic, spherical geopotential                approximation</shortName>
                    <longName>shallow-atmosphere, non-hydrostatic, spherical geopotential                approximation</longName>
                  </value>
                  <value>
                    <shortName>shallow-atmosphere, hydrostatic, spherical geopotential approximation                (primitive equations)</shortName>
                    <longName>shallow-atmosphere, hydrostatic, spherical geopotential approximation                (primitive equations)</longName>
                  </value>
                  <value>
                    <shortName>shallow-atmosphere but cos-Coriolis terms retained, non-hydrostatic,                spherical geopotential approximation</shortName>
                    <longName>shallow-atmosphere but cos-Coriolis terms retained, non-hydrostatic,                spherical geopotential approximation</longName>
                  </value>
                  <value>
                    <shortName>sound-proof: anelastic, non-hydrostatic, spherical geopotential                approximation </shortName>
                    <longName>sound-proof: anelastic, non-hydrostatic, spherical geopotential                approximation </longName>
                  </value>
                  <value>
                    <shortName>sound-proof: unified, non-hydrostatic, spherical geopotential                approximation</shortName>
                    <longName>sound-proof: unified, non-hydrostatic, spherical geopotential                approximation</longName>
                  </value>
                </values>
              </property>
          </properties>
        </property>
      </properties>
    </model>
    <model>
      <name>responsibleparty</name>
      <properties>
        <property>
          <shortName>some_other_thing</shortName>
          <longName>some other thing</longName>
          <values open="true">
            <value>
              <shortName>some other value</shortName>
              <longName>Some Other value</longName>
            </value>
          </values>
        </property>
      </properties>
    </model>
    
  </models>
</vocabulary>

<!--

    <item>
      <shortName>Dynamical Core</shortName>
      <longName>Dynamical Core</longName>
      <items>
        <item>
          <shortName>equation_set</shortName>
          <longName>Equation Set</longName>
          <values open="true">
            <value>
              <shortName>deep-atmosphere non-hydrostatic (unapproximated Euler                equations)</shortName>
              <longName>deep-atmosphere non-hydrostatic (unapproximated Euler equations)</longName>
            </value>
            <value>
              <shortName>deep-atmosphere, non-hydrostatic, spherical geopotential                approximation</shortName>
              <longName>deep-atmosphere, non-hydrostatic, spherical geopotential                approximation</longName>
            </value>
            <value>
              <shortName>deep-atmosphere, hydrostatic, spherical geopotential approximation                (quasi-hydrostatic)</shortName>
              <longName>deep-atmosphere, hydrostatic, spherical geopotential approximation                (quasi-hydrostatic)</longName>
            </value>
            <value>
              <shortName>shallow-atmosphere, non-hydrostatic, spherical geopotential                approximation</shortName>
              <longName>shallow-atmosphere, non-hydrostatic, spherical geopotential                approximation</longName>
            </value>
            <value>
              <shortName>shallow-atmosphere, hydrostatic, spherical geopotential approximation                (primitive equations)</shortName>
              <longName>shallow-atmosphere, hydrostatic, spherical geopotential approximation                (primitive equations)</longName>
            </value>
            <value>
              <shortName>shallow-atmosphere but cos-Coriolis terms retained, non-hydrostatic,                spherical geopotential approximation</shortName>
              <longName>shallow-atmosphere but cos-Coriolis terms retained, non-hydrostatic,                spherical geopotential approximation</longName>
            </value>
            <value>
              <shortName>sound-proof: anelastic, non-hydrostatic, spherical geopotential                approximation </shortName>
              <longName>sound-proof: anelastic, non-hydrostatic, spherical geopotential                approximation </longName>
            </value>
            <value>
              <shortName>sound-proof: unified, non-hydrostatic, spherical geopotential                approximation</shortName>
              <longName>sound-proof: unified, non-hydrostatic, spherical geopotential                approximation</longName>
            </value>
          </values>
        </item>
        
        <item>
          <shortName>Dycore Generic class</shortName>
          <longName>Generic class</longName>
          <values open="true">
            <value>
              <shortName>Eulerian</shortName>
              <longName>Eulerian</longName>
            </value>
            <value>
              <shortName>Eulerian with semi-Lagrangian extension in the longitudinal                direction</shortName>
              <longName>Eulerian with semi-Lagrangian extension in the longitudinal                direction</longName>
            </value>
            <value>
              <shortName>semi-Lagrangian</shortName>
              <longName>semi-Lagrangian</longName>
            </value>
            <value>
              <shortName>semi-Lagrangian, except Eulerian-type continuity equation</shortName>
              <longName>semi-Lagrangian, except Eulerian-type continuity equation</longName>
            </value>
          </values>
        </item>
        <item>
          <shortName>Type of horizontal discretization</shortName>
          <longName>Type of horizontal discretization</longName>
          <values open="true">
            <value>
              <shortName>discontinuous Galerkin</shortName>
              <longName>discontinuous Galerkin</longName>
            </value>
            <value>
              <shortName>finite difference</shortName>
              <longName>finite difference</longName>
            </value>
            <value>
              <shortName>finite element</shortName>
              <longName>finite element</longName>
            </value>
            <value>
              <shortName>finite volume</shortName>
              <longName>finite volume</longName>
            </value>
            <value>
              <shortName>finite volume and finite difference</shortName>
              <longName>finite volume and finite difference</longName>
            </value>
            <value>
              <shortName>spectral element</shortName>
              <longName>spectral element</longName>
            </value>
            <value>
              <shortName>spectral finite volume</shortName>
              <longName>spectral finite volume</longName>
            </value>
            <value>
              <shortName>spectral-transform</shortName>
              <longName>spectral-transform</longName>
            </value>
          </values>
        </item>
        <item>
          <shortName>Type of vertical discretization</shortName>
          <longName>Type of vertical discretization</longName>
          <values open="true">
            <value>
              <shortName>finite difference</shortName>
              <longName>finite difference</longName>
            </value>
            <value>
              <shortName>finite element</shortName>
              <longName>finite element</longName>
            </value>
            <value>
              <shortName>finite volume</shortName>
              <longName>finite volume</longName>
            </value>
            <value>
              <shortName>vertical remapping (with floating Lagrangian coordinate)</shortName>
              <longName>vertical remapping (with floating Lagrangian coordinate)</longName>
            </value>
          </values>
        </item>
        <item>
          <shortName>Temporal discretization (generic class)</shortName>
